source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'
<% if project_template.eql?("swift") || project_template.eql?("viper-swift") %>use_frameworks!<% end %>
inhibit_all_warnings!

target :app, :exclusive => true do
  link_with '<%= project_name %>'
<% if project_template.eql?("swift") || project_template.eql?("viper-swift") %>
  pod 'Swinject'
    
  pod 'Alamofire'
  pod 'Genome'
  
  pod 'Nuke'
  
  pod 'SwiftDate'
  pod 'SwiftyColor'
  pod 'SpringIndicator'
  pod 'SnapKit'
  pod 'AsyncSwift'

  pod 'StatefulViewController'
end
<% else %>  
  pod 'AFNetworking'
  pod 'Mantle'

  pod 'SDWebImage'
end
<% end %>

target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end

<% if enable_settings && dependency_manager_enabled?("cocoapods") %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>
