source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'
<% if project_template.eql?("swift") || project_template.eql?("swift-viper") || project_template.eql?("swift-mvvm") %>use_frameworks!<% end %>
inhibit_all_warnings!

target '<%= project_name %>' do
<% if project_template.eql?("swift") || project_template.eql?("swift-viper") || project_template.eql?("swift-mvvm") %>
  pod 'Swinject', '~> 1.1'
    
  pod 'Alamofire', '~> 3.3'
  pod 'Gloss', '~> 0.7'
  
  pod 'Nuke', '~> 3.1'
  
  pod 'SwiftDate', '~> 3.0'
  pod 'SwiftyColor', '~> 0.1'
  pod 'SpringIndicator', '~> 1.2'
  pod 'SnapKit', '~> 0.20'
  pod 'AsyncSwift', '~> 1.7'

  pod 'StatefulViewController', '~> 1.0'

  pod 'RxSwift', '~> 2.4'
  pod 'RxCocoa', '~> 2.4'
  pod 'RxAlamofire', '~> 2.2'
end
<% else %>  
  pod 'AFNetworking'
  pod 'Mantle'

  pod 'SDWebImage'
end
<% end %>

<% if enable_settings && dependency_manager_enabled?("cocoapods") %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>
       
